name = "DynamicalSystems"
defaultTargets = ["DynamicalSystems"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
weak.linter.flexible = true
weak.linter.mathlibStandardSet = true
warn.sorry = false

[[require]]
name = "verso"
scope = "leanprover"
rev = "v4.31.0-rc1"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "01cc3279731fe3f5f4d8902c77c18ac6c052342e"

[[lean_lib]]
name = "DynamicalSystems"

[[lean_exe]]
name = "generate-docs"
root = "Documentation"
