name = "DynamicalSystems"
defaultTargets = ["DynamicalSystems"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
weak.linter.flexible = true
weak.linter.mathlibStandardSet = true
warn.sorry = false

[[require]]
name = "verso"
scope = "leanprover"
rev = "v4.30.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "a694d6797b7137565ec8a361bf71e6e65dd2672c"

[[lean_lib]]
name = "DynamicalSystems"

[[lean_exe]]
name = "generate-docs"
root = "Documentation"
