name = "DynamicalSystems"
defaultTargets = ["DynamicalSystems"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
weak.linter.flexible = true
weak.linter.mathlibStandardSet = true
warn.sorry = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "DynamicalSystems"
