module

public import Mathlib.Analysis.ODE.Basic
import Mathlib.Analysis.ODE.Gronwall
import Mathlib.Analysis.ODE.PicardLindelof
import Mathlib.Analysis.ODE.ExistUnique

/-!
# Global existence for ODEs with a globally Lipschitz, bounded vector field

We prove that a continuous globally Lipschitz vector field admits a global solution.
This is a direct consequence of the construction of the Picard iteration.

This file was mainly generated by Aristotle AI.

-/

open scoped NNReal
open Metric Set

/-! ## Global existence -/

section GlobalExistence

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
  {f : ℝ → E → E} {C : ℝ} {K : ℝ≥0}

/-- Local (in fact, on an arbitrarily large compact time interval) existence, from the
Picard-Lindelöf theorem. -/
theorem exists_solution_Icc (h_lip : ∀ t, LipschitzWith K (f t))
    (h_cont : ∀ x, Continuous (f · x)) (h_bdd : ∀ t x, ‖f t x‖ ≤ C)
    (t₀ : ℝ) (x₀ : E) (R : ℝ) (hR : 0 ≤ R) :
    ∃ α : ℝ → E, α t₀ = x₀ ∧ ∀ t ∈ Icc (t₀ - R) (t₀ + R),
      HasDerivWithinAt α (f t (α t)) (Icc (t₀ - R) (t₀ + R)) t := by
  have hC : 0 ≤ C := le_trans (norm_nonneg _) (h_bdd 0 0)
  have ht₀ : t₀ ∈ Icc (t₀ - R) (t₀ + R) := ⟨by linarith, by linarith⟩
  have hpl : IsPicardLindelof f (tmin := t₀ - R) (tmax := t₀ + R) ⟨t₀, ht₀⟩ x₀
      ⟨C * R, by positivity⟩ 0 ⟨C, hC⟩ K := by
    refine ⟨fun t _ ↦ (h_lip t).lipschitzOnWith, fun x _ ↦ (h_cont x).continuousOn,
      fun t _ x _ ↦ h_bdd t x, ?_⟩
    change (C : ℝ) * max (t₀ + R - t₀) (t₀ - (t₀ - R)) ≤ (C * R : ℝ) - ((0 : ℝ≥0) : ℝ)
    rw [show t₀ + R - t₀ = R by ring, show t₀ - (t₀ - R) = R by ring, max_self]
    simp
  exact hpl.exists_eq_forall_mem_Icc_hasDerivWithinAt₀

omit [CompleteSpace E] in
/-- Two solutions with the same initial condition agree on any open interval on which
they are both defined. -/
public theorem solution_eqOn_Ioo (h_lip : ∀ t, LipschitzWith K (f t))
    {α β : ℝ → E} {t₀ a b : ℝ} (ht₀ : t₀ ∈ Ioo a b) (hαβ : α t₀ = β t₀)
    (hα : ∀ t ∈ Ioo a b, HasDerivAt α (f t (α t)) t)
    (hβ : ∀ t ∈ Ioo a b, HasDerivAt β (f t (β t)) t) :
    EqOn α β (Ioo a b) :=
  ODE_solution_unique_of_mem_Ioo (K := K) (s := fun _ ↦ univ)
    (fun t _ ↦ (h_lip t).lipschitzOnWith) ht₀
    (fun t ht ↦ ⟨hα t ht, trivial⟩) (fun t ht ↦ ⟨hβ t ht, trivial⟩) hαβ

/-- A continuous vector field that is bounded and Lipschitz in the second variable admits a
global fundamental solution. -/
public theorem exists_isIntegralCurve_of_bounded (h_lip : ∀ t, LipschitzWith K (f t))
    (h_bdd : ∀ t x, ‖f t x‖ ≤ C) (h' : Continuous f.uncurry) :
    ∃ Φ : ℝ → E → ℝ → E, ∀ t₀ x₀, IsIntegralCurve (Φ t₀ x₀) f ∧ Φ t₀ x₀ t₀ = x₀ := by
  have h_cont : ∀ x, Continuous (f · x) := fun x ↦
    h'.comp (continuous_id.prodMk continuous_const)
  -- For each initial condition and each `n : ℕ`, a solution on `[t₀ - (n+1), t₀ + (n+1)]`.
  have H : ∀ (t₀ : ℝ) (x₀ : E) (n : ℕ), ∃ α : ℝ → E, α t₀ = x₀ ∧
      ∀ t ∈ Icc (t₀ - ((n : ℝ) + 1)) (t₀ + ((n : ℝ) + 1)),
        HasDerivWithinAt α (f t (α t)) (Icc (t₀ - ((n : ℝ) + 1)) (t₀ + ((n : ℝ) + 1))) t :=
    fun t₀ x₀ n ↦ exists_solution_Icc h_lip h_cont h_bdd t₀ x₀ ((n : ℝ) + 1) (by positivity)
  choose α hα0 hα using H
  -- At interior times these are genuine solutions.
  have hderiv : ∀ (t₀ : ℝ) (x₀ : E) (n : ℕ) (t : ℝ), |t - t₀| < (n : ℝ) + 1 →
      HasDerivAt (α t₀ x₀ n) (f t (α t₀ x₀ n t)) t := by
    intro t₀ x₀ n t ht
    rw [abs_lt] at ht
    obtain ⟨h1, h2⟩ := ht
    exact (hα t₀ x₀ n t ⟨by linarith, by linarith⟩).hasDerivAt
      (Icc_mem_nhds (by linarith) (by linarith))
  -- Solutions for different `n` agree wherever both are defined.
  have hagree : ∀ (t₀ : ℝ) (x₀ : E) (m n : ℕ), m ≤ n → ∀ t : ℝ, |t - t₀| < (m : ℝ) + 1 →
      α t₀ x₀ m t = α t₀ x₀ n t := by
    intro t₀ x₀ m n hmn t ht
    have hmn' : (m : ℝ) ≤ (n : ℝ) := by exact_mod_cast hmn
    have hsub : ∀ s ∈ Ioo (t₀ - ((m : ℝ) + 1)) (t₀ + ((m : ℝ) + 1)), |s - t₀| < (m : ℝ) + 1 := by
      intro s hs
      rw [abs_lt]
      exact ⟨by linarith [hs.1], by linarith [hs.2]⟩
    have hm0 : (0 : ℝ) < (m : ℝ) + 1 := by positivity
    refine solution_eqOn_Ioo (t₀ := t₀) h_lip (a := t₀ - ((m : ℝ) + 1)) (b := t₀ + ((m : ℝ) + 1))
      ⟨by linarith, by linarith⟩
      ((hα0 _ _ _).trans (hα0 _ _ _).symm)
      (fun s hs ↦ hderiv t₀ x₀ m s (hsub s hs))
      (fun s hs ↦ hderiv t₀ x₀ n s ((hsub s hs).trans_le (by linarith))) ?_
    rw [abs_lt] at ht
    exact ⟨by linarith [ht.1], by linarith [ht.2]⟩
  refine ⟨fun t₀ x₀ t ↦ α t₀ x₀ ⌈|t - t₀|⌉₊ t, fun t₀ x₀ ↦ ⟨fun t ↦ ?_, by simp [hα0]⟩⟩
  set N : ℕ := ⌈|t - t₀|⌉₊ with hN
  have hNle : |t - t₀| ≤ (N : ℝ) := Nat.le_ceil _
  -- Near `t`, the constructed flow coincides with the single solution of index `N + 1`.
  have key : ∀ s : ℝ, |s - t| < 1 / 2 → α t₀ x₀ ⌈|s - t₀|⌉₊ s = α t₀ x₀ (N + 1) s := by
    intro s hs
    have hst : |s - t₀| ≤ (N : ℝ) + 1 / 2 := by
      calc |s - t₀| ≤ |s - t| + |t - t₀| := by
            simpa using abs_sub_le s t t₀
        _ ≤ (N : ℝ) + 1 / 2 := by linarith
    refine hagree t₀ x₀ _ (N + 1) ?_ s ?_
    · refine Nat.ceil_le.mpr ?_
      push_cast
      linarith
    · exact lt_of_le_of_lt (Nat.le_ceil _) (by linarith)
  have hev : (fun s ↦ α t₀ x₀ ⌈|s - t₀|⌉₊ s) =ᶠ[nhds t] α t₀ x₀ (N + 1) := by
    have hball : ∀ᶠ s in nhds t, |s - t| < 1 / 2 := by
      filter_upwards [Metric.ball_mem_nhds t (by norm_num : (0 : ℝ) < 1 / 2)] with s hs
      simpa [Real.dist_eq] using hs
    filter_upwards [hball] with s hs using key s hs
  have hval : α t₀ x₀ N t = α t₀ x₀ (N + 1) t := by
    simpa using key t (by norm_num)
  have hd : HasDerivAt (α t₀ x₀ (N + 1)) (f t (α t₀ x₀ (N + 1) t)) t := by
    refine hderiv t₀ x₀ (N + 1) t ?_
    push_cast
    linarith
  change HasDerivAt (fun s ↦ α t₀ x₀ ⌈|s - t₀|⌉₊ s) (f t (α t₀ x₀ N t)) t
  rw [hval]
  exact hd.congr_of_eventuallyEq hev

end GlobalExistence
